import './globals.css'
import { Poppins } from 'next/font/google';

const poppinsFont = Poppins({
  weight: ['500'],
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={`${poppinsFont.className} no-scrollbar`}>{children}</body>
    </html>
  )
}
